# ======================== Elasticsearch Configuration =========================
#

{{ $es_port := .Env.ELASTICSEARCH_PORT_TRANSPORT }}

cluster.name: {{ .Env.ELASTICSEARCH_CLUSTER_NAME }}

transport:
    host: {{ .Env.ELASTICSEARCH_ADDR_TRANSPORT }}
    tcp.port: {{ .Env.ELASTICSEARCH_PORT_TRANSPORT }}
    tcp.connect_timeout: 2s

discovery.zen:
    hosts_provider: file
    minimum_master_nodes: 1
    ping_timeout: 3s
    join_timeout: 6s
    fd:
        ping_timeout: 3s
        ping_interval: 1s
        ping_retries: 3

node:
    master: {{ .Env.ELASTICSEARCH_NODE_MASTER }}
    data: {{ .Env.ELASTICSEARCH_NODE_DATA }}
    name: {{ .Env.HOSTNAME }}

http:
    enabled: true
    cors.enabled: false
    port: {{ .Env.ELASTICSEARCH_PORT_HTTP }}
    host: {{ .Env.ELASTICSEARCH_ADDR_HTTP }}

path:
    data: /data
    logs: /logs


search.default_search_timeout: 30s
search.low_level_cancellation: true
